services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  tcp_server:
    build:
      context: .
      dockerfile: Dockerfile.tcp
    volumes:
      - ./app:/app
    ports:
      - "5500:5500"
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    volumes:
      - ./app:/app
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locationdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
